services:
  api:
    image: ghcr.io/deboschr/digital-signage-api:latest
    container_name: cms-api
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
      - "0.0.0.0:9000:9000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ../media:/app/media
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 15s
      timeout: 3s
      retries: 3

  db:
    image: mysql:8.0
    container_name: cms-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    # ⚠️ jangan expose ke host, biar tidak bentrok dengan MySQL bawaan server
    # kalau butuh akses manual dari host, baru buka port misalnya "3307:3306"

volumes:
  db_data:
