services:
  api:
    image: ghcr.io/deboschr/digital-signage-api:latest
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/health"]
      interval: 15s
      timeout: 3s
      retries: 3
